<?php

/*
 * @category   FME
 * @package    FME_Canonical
 * @author     Shaheer Ali
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

?>
<?php if (Mage::getStoreConfig('advanced/modules_disable_output/Ffuenf_Canonical')==0) { ?>
 <link rel="canonical" href="<?php echo htmlspecialchars(Mage::helper('canonical')->getHeadCanonicalUrl()) ?>" />
<?php } ?>