<?php

/*
 * @category   FME
 * @package    FME_Canonical
 * @author     Shaheer Ali
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

?>
<?php if (Mage::helper('ffuenf_canonical')->isExtensionActive() && !Mage::helper('ffuenf_canonical')->isProductCanonicalActive()) { ?>
 XXX<link rel="canonical" href="<?php echo htmlspecialchars(Mage::helper('ffuenf_canonical')->getHeadProductCanonicalUrl()) ?>" />
<?php } ?>